# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa9b53c45aa0fcf8dc0cf7daba1eba073dd9c2bc5d4fc068c0c6bd1641c3bbaffed995a1316ecb2811a8f03ccf3564c109f6dc7b6a2e64fe5a134c7cc9d30225

test:
  secret_key_base: e4892616b4550f215ebe1c3a7097119e5c38248ddc170db65062a43bc100c33251c28f3786b378fca32dc93328d5c637e44ed6568c5bd05e6debb5382939549d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
